studylist2_pureproduce = [
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>EMERALD</span></p>","data":{"type":"old","condition":"produce","category":"precious stone","word":"EMERALD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SAPPHIRE</span></p>","data":{"type":"old","condition":"produce","category":"precious stone","word":"SAPPHIRE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>AMETHYST</span></p>","data":{"type":"old","condition":"produce","category":"precious stone","word":"AMETHYST"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>RUBY</span></p>","data":{"type":"old","condition":"produce","category":"precious stone","word":"RUBY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>PEARL</span></p>","data":{"type":"old","condition":"produce","category":"precious stone","word":"PEARL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>TURQUOISE</span></p>","data":{"type":"old","condition":"produce","category":"precious stone","word":"TURQUOISE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>COUCH</span></p>","data":{"type":"old","condition":"produce","category":"article of furniture","word":"COUCH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>BED</span></p>","data":{"type":"old","condition":"produce","category":"article of furniture","word":"BED"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>CHAIR</span></p>","data":{"type":"old","condition":"produce","category":"article of furniture","word":"CHAIR"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>LOVESEAT</span></p>","data":{"type":"old","condition":"produce","category":"article of furniture","word":"LOVESEAT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>ARMOIRE</span></p>","data":{"type":"old","condition":"produce","category":"article of furniture","word":"ARMOIRE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>OTTOMAN</span></p>","data":{"type":"old","condition":"produce","category":"article of furniture","word":"OTTOMAN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>HAMMER</span></p>","data":{"type":"old","condition":"produce","category":"carpenter tool","word":"HAMMER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SCREWDRIVER</span></p>","data":{"type":"old","condition":"produce","category":"carpenter tool","word":"SCREWDRIVER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>WRENCH</span></p>","data":{"type":"old","condition":"produce","category":"carpenter tool","word":"WRENCH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>DRILL</span></p>","data":{"type":"old","condition":"produce","category":"carpenter tool","word":"DRILL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SAW</span></p>","data":{"type":"old","condition":"produce","category":"carpenter tool","word":"SAW"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>PLIERS</span></p>","data":{"type":"old","condition":"produce","category":"carpenter tool","word":"PLIERS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>PRIEST</span></p>","data":{"type":"old","condition":"produce","category":"member of clergy","word":"PRIEST"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>NUN</span></p>","data":{"type":"old","condition":"produce","category":"member of clergy","word":"NUN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>MONK</span></p>","data":{"type":"old","condition":"produce","category":"member of clergy","word":"MONK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>BISHOP</span></p>","data":{"type":"old","condition":"produce","category":"member of clergy","word":"BISHOP"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>PREACHER</span></p>","data":{"type":"old","condition":"produce","category":"member of clergy","word":"PREACHER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>DEACON</span></p>","data":{"type":"old","condition":"produce","category":"member of clergy","word":"DEACON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>GAS</span></p>","data":{"type":"old","condition":"produce","category":"type of fuel","word":"GAS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>DIESEL</span></p>","data":{"type":"old","condition":"produce","category":"type of fuel","word":"DIESEL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>OIL</span></p>","data":{"type":"old","condition":"produce","category":"type of fuel","word":"OIL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SOLAR</span></p>","data":{"type":"old","condition":"produce","category":"type of fuel","word":"SOLAR"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>COAL</span></p>","data":{"type":"old","condition":"produce","category":"type of fuel","word":"COAL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>KEROSENE</span></p>","data":{"type":"old","condition":"produce","category":"type of fuel","word":"KEROSENE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>OXYGEN</span></p>","data":{"type":"old","condition":"produce","category":"chemical element","word":"OXYGEN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>HYDROGEN</span></p>","data":{"type":"old","condition":"produce","category":"chemical element","word":"HYDROGEN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SODIUM</span></p>","data":{"type":"old","condition":"produce","category":"chemical element","word":"SODIUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>POTASSIUM</span></p>","data":{"type":"old","condition":"produce","category":"chemical element","word":"POTASSIUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>ARGON</span></p>","data":{"type":"old","condition":"produce","category":"chemical element","word":"ARGON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>CALCIUM</span></p>","data":{"type":"old","condition":"produce","category":"chemical element","word":"CALCIUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>EAGLE</span></p>","data":{"type":"old","condition":"produce","category":"bird","word":"EAGLE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>HUMMINGBIRD</span></p>","data":{"type":"old","condition":"produce","category":"bird","word":"HUMMINGBIRD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>BLUEJAY</span></p>","data":{"type":"old","condition":"produce","category":"bird","word":"BLUEJAY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>HAWK</span></p>","data":{"type":"old","condition":"produce","category":"bird","word":"HAWK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>OSTRICH</span></p>","data":{"type":"old","condition":"produce","category":"bird","word":"OSTRICH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>DUCK</span></p>","data":{"type":"old","condition":"produce","category":"bird","word":"DUCK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>JUICE</span></p>","data":{"type":"old","condition":"produce","category":"nonalcoholic beverage","word":"JUICE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>MILK</span></p>","data":{"type":"old","condition":"produce","category":"nonalcoholic beverage","word":"MILK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>WATER</span></p>","data":{"type":"old","condition":"produce","category":"nonalcoholic beverage","word":"WATER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>COFFEE</span></p>","data":{"type":"old","condition":"produce","category":"nonalcoholic beverage","word":"COFFEE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>POP</span></p>","data":{"type":"old","condition":"produce","category":"nonalcoholic beverage","word":"POP"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>LEMONADE</span></p>","data":{"type":"old","condition":"produce","category":"nonalcoholic beverage","word":"LEMONADE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>BALLET</span></p>","data":{"type":"old","condition":"produce","category":"type of dance","word":"BALLET"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>TANGO</span></p>","data":{"type":"old","condition":"produce","category":"type of dance","word":"TANGO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>BALLROOM</span></p>","data":{"type":"old","condition":"produce","category":"type of dance","word":"BALLROOM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SWING</span></p>","data":{"type":"old","condition":"produce","category":"type of dance","word":"SWING"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SALSA</span></p>","data":{"type":"old","condition":"produce","category":"type of dance","word":"SALSA"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>JAZZ</span></p>","data":{"type":"old","condition":"produce","category":"type of dance","word":"JAZZ"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SANDALS</span></p>","data":{"type":"old","condition":"produce","category":"footware","word":"SANDALS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>BOOTS</span></p>","data":{"type":"old","condition":"produce","category":"footware","word":"BOOTS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>MOCCASINS</span></p>","data":{"type":"old","condition":"produce","category":"footware","word":"MOCCASINS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>HEELS</span></p>","data":{"type":"old","condition":"produce","category":"footware","word":"HEELS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>FLIPFLOPS</span></p>","data":{"type":"old","condition":"produce","category":"footware","word":"FLIPFLOPS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>CLOGS</span></p>","data":{"type":"old","condition":"produce","category":"footware","word":"CLOGS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>YACHT</span></p>","data":{"type":"old","condition":"produce","category":"type of boat","word":"YACHT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>KAYAK</span></p>","data":{"type":"old","condition":"produce","category":"type of boat","word":"KAYAK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>CANOE</span></p>","data":{"type":"old","condition":"produce","category":"type of boat","word":"CANOE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>SUBMARINE</span></p>","data":{"type":"old","condition":"produce","category":"type of boat","word":"SUBMARINE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>TITANIC</span></p>","data":{"type":"old","condition":"produce","category":"type of boat","word":"TITANIC"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>CARGO</span></p>","data":{"type":"old","condition":"produce","category":"type of boat","word":"CARGO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>QUARTERBACK</span></p>","data":{"type":"old","condition":"produce","category":"football position","word":"QUARTERBACK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>LINEMAN</span></p>","data":{"type":"old","condition":"produce","category":"football position","word":"LINEMAN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>RECEIVER</span></p>","data":{"type":"old","condition":"produce","category":"football position","word":"RECEIVER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>GUARD</span></p>","data":{"type":"old","condition":"produce","category":"football position","word":"GUARD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>TACKLE</span></p>","data":{"type":"old","condition":"produce","category":"football position","word":"TACKLE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: green'>OFFENSE</span></p>","data":{"type":"old","condition":"produce","category":"football position","word":"OFFENSE"}},
]