studylist1_pureread = [
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>EMERALD</span></p>","data":{"type":"old","condition":"read","category":"precious stone","word":"EMERALD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SAPPHIRE</span></p>","data":{"type":"old","condition":"read","category":"precious stone","word":"SAPPHIRE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>AMETHYST</span></p>","data":{"type":"old","condition":"read","category":"precious stone","word":"AMETHYST"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>RUBY</span></p>","data":{"type":"old","condition":"read","category":"precious stone","word":"RUBY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PEARL</span></p>","data":{"type":"old","condition":"read","category":"precious stone","word":"PEARL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TURQUOISE</span></p>","data":{"type":"old","condition":"read","category":"precious stone","word":"TURQUOISE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COUCH</span></p>","data":{"type":"old","condition":"read","category":"article of furniture","word":"COUCH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BED</span></p>","data":{"type":"old","condition":"read","category":"article of furniture","word":"BED"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CHAIR</span></p>","data":{"type":"old","condition":"read","category":"article of furniture","word":"CHAIR"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>LOVESEAT</span></p>","data":{"type":"old","condition":"read","category":"article of furniture","word":"LOVESEAT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>ARMOIRE</span></p>","data":{"type":"old","condition":"read","category":"article of furniture","word":"ARMOIRE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OTTOMAN</span></p>","data":{"type":"old","condition":"read","category":"article of furniture","word":"OTTOMAN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HAMMER</span></p>","data":{"type":"old","condition":"read","category":"carpenter tool","word":"HAMMER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SCREWDRIVER</span></p>","data":{"type":"old","condition":"read","category":"carpenter tool","word":"SCREWDRIVER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>WRENCH</span></p>","data":{"type":"old","condition":"read","category":"carpenter tool","word":"WRENCH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>DRILL</span></p>","data":{"type":"old","condition":"read","category":"carpenter tool","word":"DRILL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SAW</span></p>","data":{"type":"old","condition":"read","category":"carpenter tool","word":"SAW"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PLIERS</span></p>","data":{"type":"old","condition":"read","category":"carpenter tool","word":"PLIERS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PRIEST</span></p>","data":{"type":"old","condition":"read","category":"member of clergy","word":"PRIEST"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>NUN</span></p>","data":{"type":"old","condition":"read","category":"member of clergy","word":"NUN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>MONK</span></p>","data":{"type":"old","condition":"read","category":"member of clergy","word":"MONK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BISHOP</span></p>","data":{"type":"old","condition":"read","category":"member of clergy","word":"BISHOP"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PREACHER</span></p>","data":{"type":"old","condition":"read","category":"member of clergy","word":"PREACHER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>DEACON</span></p>","data":{"type":"old","condition":"read","category":"member of clergy","word":"DEACON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>GAS</span></p>","data":{"type":"old","condition":"read","category":"type of fuel","word":"GAS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>DIESEL</span></p>","data":{"type":"old","condition":"read","category":"type of fuel","word":"DIESEL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OIL</span></p>","data":{"type":"old","condition":"read","category":"type of fuel","word":"OIL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SOLAR</span></p>","data":{"type":"old","condition":"read","category":"type of fuel","word":"SOLAR"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COAL</span></p>","data":{"type":"old","condition":"read","category":"type of fuel","word":"COAL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>KEROSENE</span></p>","data":{"type":"old","condition":"read","category":"type of fuel","word":"KEROSENE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OXYGEN</span></p>","data":{"type":"old","condition":"read","category":"chemical element","word":"OXYGEN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HYDROGEN</span></p>","data":{"type":"old","condition":"read","category":"chemical element","word":"HYDROGEN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SODIUM</span></p>","data":{"type":"old","condition":"read","category":"chemical element","word":"SODIUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>POTASSIUM</span></p>","data":{"type":"old","condition":"read","category":"chemical element","word":"POTASSIUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>ARGON</span></p>","data":{"type":"old","condition":"read","category":"chemical element","word":"ARGON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CALCIUM</span></p>","data":{"type":"old","condition":"read","category":"chemical element","word":"CALCIUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>EAGLE</span></p>","data":{"type":"old","condition":"read","category":"bird","word":"EAGLE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HUMMINGBIRD</span></p>","data":{"type":"old","condition":"read","category":"bird","word":"HUMMINGBIRD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BLUEJAY</span></p>","data":{"type":"old","condition":"read","category":"bird","word":"BLUEJAY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HAWK</span></p>","data":{"type":"old","condition":"read","category":"bird","word":"HAWK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OSTRICH</span></p>","data":{"type":"old","condition":"read","category":"bird","word":"OSTRICH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>DUCK</span></p>","data":{"type":"old","condition":"read","category":"bird","word":"DUCK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>JUICE</span></p>","data":{"type":"old","condition":"read","category":"nonalcoholic beverage","word":"JUICE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>MILK</span></p>","data":{"type":"old","condition":"read","category":"nonalcoholic beverage","word":"MILK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>WATER</span></p>","data":{"type":"old","condition":"read","category":"nonalcoholic beverage","word":"WATER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COFFEE</span></p>","data":{"type":"old","condition":"read","category":"nonalcoholic beverage","word":"COFFEE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>POP</span></p>","data":{"type":"old","condition":"read","category":"nonalcoholic beverage","word":"POP"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>LEMONADE</span></p>","data":{"type":"old","condition":"read","category":"nonalcoholic beverage","word":"LEMONADE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BALLET</span></p>","data":{"type":"old","condition":"read","category":"type of dance","word":"BALLET"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TANGO</span></p>","data":{"type":"old","condition":"read","category":"type of dance","word":"TANGO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BALLROOM</span></p>","data":{"type":"old","condition":"read","category":"type of dance","word":"BALLROOM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SWING</span></p>","data":{"type":"old","condition":"read","category":"type of dance","word":"SWING"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SALSA</span></p>","data":{"type":"old","condition":"read","category":"type of dance","word":"SALSA"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>JAZZ</span></p>","data":{"type":"old","condition":"read","category":"type of dance","word":"JAZZ"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SANDALS</span></p>","data":{"type":"old","condition":"read","category":"footware","word":"SANDALS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BOOTS</span></p>","data":{"type":"old","condition":"read","category":"footware","word":"BOOTS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>MOCCASINS</span></p>","data":{"type":"old","condition":"read","category":"footware","word":"MOCCASINS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HEELS</span></p>","data":{"type":"old","condition":"read","category":"footware","word":"HEELS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>FLIPFLOPS</span></p>","data":{"type":"old","condition":"read","category":"footware","word":"FLIPFLOPS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CLOGS</span></p>","data":{"type":"old","condition":"read","category":"footware","word":"CLOGS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>YACHT</span></p>","data":{"type":"old","condition":"read","category":"type of boat","word":"YACHT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>KAYAK</span></p>","data":{"type":"old","condition":"read","category":"type of boat","word":"KAYAK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CANOE</span></p>","data":{"type":"old","condition":"read","category":"type of boat","word":"CANOE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SUBMARINE</span></p>","data":{"type":"old","condition":"read","category":"type of boat","word":"SUBMARINE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TITANIC</span></p>","data":{"type":"old","condition":"read","category":"type of boat","word":"TITANIC"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CARGO</span></p>","data":{"type":"old","condition":"read","category":"type of boat","word":"CARGO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>QUARTERBACK</span></p>","data":{"type":"old","condition":"read","category":"football position","word":"QUARTERBACK"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>LINEMAN</span></p>","data":{"type":"old","condition":"read","category":"football position","word":"LINEMAN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>RECEIVER</span></p>","data":{"type":"old","condition":"read","category":"football position","word":"RECEIVER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>GUARD</span></p>","data":{"type":"old","condition":"read","category":"football position","word":"GUARD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TACKLE</span></p>","data":{"type":"old","condition":"read","category":"football position","word":"TACKLE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OFFENSE</span></p>","data":{"type":"old","condition":"read","category":"football position","word":"OFFENSE"}},
]