studylist3_pureread = [
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>STEEL</span></p>","data":{"type":"old","condition":"read","category":"metal","word":"STEEL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>IRON</span></p>","data":{"type":"old","condition":"read","category":"metal","word":"IRON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SILVER</span></p>","data":{"type":"old","condition":"read","category":"metal","word":"SILVER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COPPER</span></p>","data":{"type":"old","condition":"read","category":"metal","word":"COPPER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BRONZE</span></p>","data":{"type":"old","condition":"read","category":"metal","word":"BRONZE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>ALUMINUM</span></p>","data":{"type":"old","condition":"read","category":"metal","word":"ALUMINUM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>LIEUTENANT</span></p>","data":{"type":"old","condition":"read","category":"military title","word":"LIEUTENANT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PRIVATE</span></p>","data":{"type":"old","condition":"read","category":"military title","word":"PRIVATE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OFFICER</span></p>","data":{"type":"old","condition":"read","category":"military title","word":"OFFICER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COMMANDER</span></p>","data":{"type":"old","condition":"read","category":"military title","word":"COMMANDER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CAPTAIN</span></p>","data":{"type":"old","condition":"read","category":"military title","word":"CAPTAIN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CADET</span></p>","data":{"type":"old","condition":"read","category":"military title","word":"CADET"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COTTON</span></p>","data":{"type":"old","condition":"read","category":"type of fabric","word":"COTTON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>WOOL</span></p>","data":{"type":"old","condition":"read","category":"type of fabric","word":"WOOL"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>DENIM</span></p>","data":{"type":"old","condition":"read","category":"type of fabric","word":"DENIM"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CASHMERE</span></p>","data":{"type":"old","condition":"read","category":"type of fabric","word":"CASHMERE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SUEDE</span></p>","data":{"type":"old","condition":"read","category":"type of fabric","word":"SUEDE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>NYLON</span></p>","data":{"type":"old","condition":"read","category":"type of fabric","word":"NYLON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>ORANGE</span></p>","data":{"type":"old","condition":"read","category":"fruit","word":"ORANGE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PEACH</span></p>","data":{"type":"old","condition":"read","category":"fruit","word":"PEACH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>RASPBERRY</span></p>","data":{"type":"old","condition":"read","category":"fruit","word":"RASPBERRY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CHERRY</span></p>","data":{"type":"old","condition":"read","category":"fruit","word":"CHERRY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CANTALOUPE</span></p>","data":{"type":"old","condition":"read","category":"fruit","word":"CANTALOUPE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>KIWI</span></p>","data":{"type":"old","condition":"read","category":"fruit","word":"KIWI"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>MOUNTAIN</span></p>","data":{"type":"old","condition":"read","category":"natural earth formation","word":"MOUNTAIN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>OCEAN</span></p>","data":{"type":"old","condition":"read","category":"natural earth formation","word":"OCEAN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>VOLCANO</span></p>","data":{"type":"old","condition":"read","category":"natural earth formation","word":"VOLCANO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CLIFF</span></p>","data":{"type":"old","condition":"read","category":"natural earth formation","word":"CLIFF"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BEACH</span></p>","data":{"type":"old","condition":"read","category":"natural earth formation","word":"BEACH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CANYON</span></p>","data":{"type":"old","condition":"read","category":"natural earth formation","word":"CANYON"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TORNADO</span></p>","data":{"type":"old","condition":"read","category":"weather phenomenon","word":"TORNADO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>RAIN</span></p>","data":{"type":"old","condition":"read","category":"weather phenomenon","word":"RAIN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SNOW</span></p>","data":{"type":"old","condition":"read","category":"weather phenomenon","word":"SNOW"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>EARTHQUAKE</span></p>","data":{"type":"old","condition":"read","category":"weather phenomenon","word":"EARTHQUAKE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>DROUGHT</span></p>","data":{"type":"old","condition":"read","category":"weather phenomenon","word":"DROUGHT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SLEET</span></p>","data":{"type":"old","condition":"read","category":"weather phenomenon","word":"SLEET"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SHIRT</span></p>","data":{"type":"old","condition":"read","category":"article of clothing","word":"SHIRT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PANTS</span></p>","data":{"type":"old","condition":"read","category":"article of clothing","word":"PANTS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SKIRT</span></p>","data":{"type":"old","condition":"read","category":"article of clothing","word":"SKIRT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SOCKS</span></p>","data":{"type":"old","condition":"read","category":"article of clothing","word":"SOCKS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SWEATER</span></p>","data":{"type":"old","condition":"read","category":"article of clothing","word":"SWEATER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COAT</span></p>","data":{"type":"old","condition":"read","category":"article of clothing","word":"COAT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PIANO</span></p>","data":{"type":"old","condition":"read","category":"musical instrument","word":"PIANO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>VIOLIN</span></p>","data":{"type":"old","condition":"read","category":"musical instrument","word":"VIOLIN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>GUITAR</span></p>","data":{"type":"old","condition":"read","category":"musical instrument","word":"GUITAR"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>BANJO</span></p>","data":{"type":"old","condition":"read","category":"musical instrument","word":"BANJO"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TRUMPET</span></p>","data":{"type":"old","condition":"read","category":"musical instrument","word":"TRUMPET"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SAXOPHONE</span></p>","data":{"type":"old","condition":"read","category":"musical instrument","word":"SAXOPHONE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CARROT</span></p>","data":{"type":"old","condition":"read","category":"vegetable","word":"CARROT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CAULIFLOWER</span></p>","data":{"type":"old","condition":"read","category":"vegetable","word":"CAULIFLOWER"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>SPINACH</span></p>","data":{"type":"old","condition":"read","category":"vegetable","word":"SPINACH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>ZUCCHINI</span></p>","data":{"type":"old","condition":"read","category":"vegetable","word":"ZUCCHINI"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CORN</span></p>","data":{"type":"old","condition":"read","category":"vegetable","word":"CORN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CELERY</span></p>","data":{"type":"old","condition":"read","category":"vegetable","word":"CELERY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>FLY</span></p>","data":{"type":"old","condition":"read","category":"insect","word":"FLY"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>ANT</span></p>","data":{"type":"old","condition":"read","category":"insect","word":"ANT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>MOTH</span></p>","data":{"type":"old","condition":"read","category":"insect","word":"MOTH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>GNAT</span></p>","data":{"type":"old","condition":"read","category":"insect","word":"GNAT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CENTIPEDE</span></p>","data":{"type":"old","condition":"read","category":"insect","word":"CENTIPEDE"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HORNET</span></p>","data":{"type":"old","condition":"read","category":"insect","word":"HORNET"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TROUT</span></p>","data":{"type":"old","condition":"read","category":"fish","word":"TROUT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>HALIBUT</span></p>","data":{"type":"old","condition":"read","category":"fish","word":"HALIBUT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>PERCH</span></p>","data":{"type":"old","condition":"read","category":"fish","word":"PERCH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>CATFISH</span></p>","data":{"type":"old","condition":"read","category":"fish","word":"CATFISH"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TUNA</span></p>","data":{"type":"old","condition":"read","category":"fish","word":"TUNA"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>COD</span></p>","data":{"type":"old","condition":"read","category":"fish","word":"COD"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>TEXAS</span></p>","data":{"type":"old","condition":"read","category":"state","word":"TEXAS"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>VERMONT</span></p>","data":{"type":"old","condition":"read","category":"state","word":"VERMONT"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>LOUISIANA</span></p>","data":{"type":"old","condition":"read","category":"state","word":"LOUISIANA"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>MICHIGAN</span></p>","data":{"type":"old","condition":"read","category":"state","word":"MICHIGAN"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>IOWA</span></p>","data":{"type":"old","condition":"read","category":"state","word":"IOWA"}},
{"stimulus":"<p style='font-size: 48px;'><span style='color: red'>FLORIDA</span></p>","data":{"type":"old","condition":"read","category":"state","word":"FLORIDA"}},
]